# Reivew 2 - Topics
1. Factorization A = LU,
2. Transposes, Permutations, Vector Space
3. Column Space and Null Space

In [1]:
import numpy as np
from scipy import linalg

In [2]:
# https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/ax-b-and-the-four-subspaces/factorization-into-a-lu/MIT18_06SCF11_Ses1.4sol.pdf
# Problem 4.1

A = np.array([[1,3,0],
            [2,4,0],
            [2,0,1]])
p,l,u = linalg.lu(A)

In [3]:
p,l,u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 1.  ,  1.  ,  0.  ],
        [ 0.5 , -0.25,  1.  ]]),
 array([[ 2.  ,  4.  ,  0.  ],
        [ 0.  , -4.  ,  1.  ],
        [ 0.  ,  0.  ,  0.25]]))

What we discover here is that scipy linalg create another decomposition, different than the one showed on the solution. Looking at permutation matrix "p", it seems that row exchanges were performed. This becomes PA = LU

In [4]:
A == p.dot(l).dot(u) #answer checks out

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# review of matrix operations
print("A")
A

A


array([[1, 3, 0],
       [2, 4, 0],
       [2, 0, 1]])

In [6]:
print("A_t")
A.transpose()

A_t


array([[1, 2, 2],
       [3, 4, 0],
       [0, 0, 1]])

In [7]:
print("I")
np.identity(3)

I


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])